parameters:
    kunstmaan_search.transformers.nodetransformerclass: Kunstmaan\SearchBundle\Transformers\NodeTransformer
    kunstmaan_search.transformers.elasticatransformerclass: Kunstmaan\SearchBundle\Transformers\ElasticaTransformer
    kunstmaan_search.entity.website: Kunstmaan\AdminNodeBundle\Entity\NodeTranslation
    kunstmaan_search.website_custom_mappings:
        content:
            handlerclass: Kunstmaan\AdminNodeBundle\Entity\NodeTranslation
            handlermethod: getSearchContentForNode
        parents:
            handlerclass: Kunstmaan\AdminNodeBundle\Entity\NodeTranslation
            handlermethod: getParentsAndSelfForNode

foq_elastica:
    clients:
        default: { host: localhost, port: %searchport% }
    indexes:
        %searchindexname%:
            client: default
            types:
                page:
                    mappings:
                        title: { analyzer: snowball }
                        id:
                        lang:
                        parents: { analyzer: whitespace }
                        content: { analyzer: snowball }
                    persistence:
                        driver: orm
                        provider:
                        model: Kunstmaan\AdminNodeBundle\Entity\NodeTranslation
                        model_to_elastica_transformer:
                            service: kunstmaan_search.transformers.nodetransformer
                        elastica_to_model_transformer:
                            service: kunstmaan_search.transformers.elasticatransformer
                        listener:
                        finder:

