parameters:
    kunstmaan_search.transformers.nodetransformerclass: Kunstmaan\SearchBundle\Transformers\NodeTransformer
    kunstmaan_search.transformers.elasticatransformerclass: Kunstmaan\SearchBundle\Transformers\ElasticaTransformer
    kunstmaan_search.entity.website: Kunstmaan\NodeBundle\Entity\NodeTranslation
    kunstmaan_search.website_custom_mappings:
        content:
            handlerclass: Kunstmaan\SearchBundle\Helper\NodeContentSearcher
            handlermethod: getSearchContentForNode
        parents:
            handlerclass: Kunstmaan\SearchBundle\Helper\NodeContentSearcher
            handlermethod: getParentsAndSelfForNode

twig:
    globals:
        searchbundleisset: true

foq_elastica:
    clients:
        default: { host: localhost, port: %searchport% }
    indexes:
        %searchindexname%:
            client: default
            types:
                page:
                    mappings:
                        title: { analyzer: snowball }
                        id:
                        lang:
                        parents: { analyzer: whitespace }
                        content: { analyzer: snowball, store:'yes',  "term_vector" : "with_positions_offsets" }
                    persistence:
                        driver: orm
                        provider:
                              query_builder_method: getOnlineNodes
                        model: Kunstmaan\NodeBundle\Entity\NodeTranslation
                        model_to_elastica_transformer:
                            service: kunstmaan_search.transformers.nodetransformer
                        elastica_to_model_transformer:
                            service: kunstmaan_search.transformers.elasticatransformer
                        listener: ~
                        finder: ~

