parameters:
    kunstmaan_search:
        analyzer_languages:
            "ar" : "arabic"
            "hy" : "armenian"
            "eu" : "basque"
            "bg" : "bulgarian"
            "ca" : "catalan"
            "zh" : "chinese"
            "cs" : "czech"
            "da" : "danish"
            "nl" : "dutch"
            "en" : "english"
            "fi" : "finnish"
            "fr" : "french"
            "gl" : "galician"
            "de" : "german"
            "el" : "greek"
            "hi" : "hindi"
            "hu" : "hungarian"
            "id" : "indonesian"
            "it" : "italian"
            "no" : "norwegian"
            "fa" : "persian"
            "pt" : "portuguese"
            "ro" : "romanian"
            "ru" : "russian"
            "es" : "spanish"
            "sv" : "swedish"
            "tr" : "turkish"
            "th" : "thai"