services:
    kunstmaan_search.transformers.nodetransformer:
        class: %kunstmaan_search.transformers.nodetransformerclass%
        arguments:
            - { container: @service_container }

    kunstmaan_search.transformers.elasticatransformer:
        class: %kunstmaan_search.transformers.elasticatransformerclass%
        arguments: [@doctrine.orm.entity_manager, %kunstmaan_search.entity.website%, [identifier: id, hydrate: true]]

    kunstmaan_search.menu.adaptor:
        class: Kunstmaan\SearchBundle\Helper\Menu\SearchMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
