parameters:
    kunstmaan_search.hostname: "localhost"
    kunstmaan_search.port: 9200
    kunstmaan_search.indexer_chain.class: Kunstmaan\SearchBundle\Service\SearchConfigurationChain

services:

    kunstmaan_search.sherlock:
        class: Kunstmaan\SearchBundle\Sherlock\SherlockImpl
        arguments: [%kunstmaan_search.hostname%, %kunstmaan_search.port%]

    Kunstmaan_search.indexer_chain:
        class: "%kunstmaan_search.indexer_chain.class%"

    kunstmaan_search.indexer.node:
        class: Kunstmaan\SearchBundle\Service\NodeSearchConfiguration
        arguments: ["@service_container", "@kunstmaan_search.sherlock"]
        tags:
            - { name: kunstmaan_search.indexer, alias : Node }