parameters:
    kunstmaan_search.hostname : "localhost"
    kunstmaan_search.port : 9200

services:

    kunstmaan_search.sherlock:
        class: Kunstmaan\SearchBundle\Sherlock\SherlockImpl
        arguments: [%kunstmaan_search.hostname%, %kunstmaan_search.port%]

    kunstmaan_search.twig.extension:
        class: Kunstmaan\SearchBundle\Twig\Extension\TrimHighlightTwigExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
