parameters:
    kunstmaan_search.hostname: "localhost"
    kunstmaan_search.port: 9200
    kunstmaan_search.searchprovider: "Sherlock"
    kunstmaan_search.searchconfiguration_chain.class: Kunstmaan\SearchBundle\Configuration\SearchConfigurationChain
    kunstmaan_search.searchprovider_chain.class: Kunstmaan\SearchBundle\Provider\SearchProviderChain

services:

    kunstmaan_search.search:
        arguments: ["@kunstmaan_search.searchprovider_chain", %searchindexprefix%, "@kunstmaan_search.searchprovider"]
        class: Kunstmaan\SearchBundle\Search\Search

    # Providers

    Kunstmaan_search.searchprovider_chain:
        class: "%kunstmaan_search.searchprovider_chain.class%"

    kunstmaan_search.searchprovider.sherlock:
        class: Kunstmaan\SearchBundle\Sherlock\SherlockSearchProvider
        arguments: [%kunstmaan_search.hostname%, %kunstmaan_search.port%]
        tags:
            - { name: kunstmaan_search.searchprovider, alias: Sherlock}

    #Configurations

    Kunstmaan_search.searchconfiguration_chain:
        class: "%kunstmaan_search.searchconfiguration_chain.class%"
